### PR TITLE
add magnifier for book image

### LINKED ISSUE #114: Image Magnifier Glass Needed In Book Details Component
Screenshot 2021-10-12 132310

- It would be really great if user can magnify on hover over image to get all details.
- An Image Magnifier Glass will be Great.
- Refer This to Know how to make It work : [How To Create an Image Magnifier](https://www.w3schools.com/howto/howto_js_image_magnifier_glass.asp)

### PR DESCRIPTION
**Pull request by yash-jain24**
resolves #114

### CODE REVIEW

**Review by Mrhb787 — CHANGES_REQUESTED** [review]
- The Magnifier Works Fine but there is an issue when we switch to other image the magnifier is still showing the old image and does not magnify the new image.

#### Possible Reasons could be use of `onLoad()` event or some `url` issue.

- Ping me if you face issues fixing it.

**Comment by yash-jain24** [comment]
img1

img2

img3

**Comment by Mrhb787** [comment]
Ok I will again check it out maybe there have been some issue. Thanks for reporting.

**Review by Mrhb787 — APPROVED** [review]

**Comment by Mrhb787** [comment]
Greak Work @yash-jain24

**Comment by yash-jain24** [comment]
So did it worked?

**Pull request merged**
